{
  "arch": "x86_64",
  "build": "py312h6a678d5_0",
  "build_number": 0,
  "channel": "https://repo.anaconda.com/pkgs/main/linux-64",
  "constrains": [],
  "depends": [
    "libgcc-ng >=11.2.0",
    "libstdcxx-ng >=11.2.0",
    "python >=3.12,<3.13.0a0",
    "unixodbc >=2.3.11,<2.4.0a0"
  ],
  "fn": "pyodbc-5.1.0-py312h6a678d5_0.conda",
  "license": "MIT-0",
  "license_family": "MIT",
  "md5": "64de57a5d4d49aac0d0da25a9162354f",
  "name": "pyodbc",
  "platform": "linux",
  "sha256": "c84b33a06f4b6f339f0a0c9182c596f755a660cfba101fb45c371345efb859fb",
  "size": 86306,
  "subdir": "linux-64",
  "timestamp": 1725560256000,
  "url": "https://repo.anaconda.com/pkgs/main/linux-64/pyodbc-5.1.0-py312h6a678d5_0.conda",
  "version": "5.1.0"
}